[package]
name = "databend-common-formats"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[dependencies] # In alphabetical order
aho-corasick = { version = "1.0.1" }
async-trait = { workspace = true }
base64 = "0.21.0"
bstr = "1.0.1"
chrono-tz = { workspace = true }
geozero = { workspace = true }
hex = "0.4.3"
lexical-core = "0.8.5"
match-template = { workspace = true }
micromarshal = "0.4.0"
num = "0.4.0"
num-traits = "0.2.15"
ordered-float = { workspace = true }
roaring = { version = "0.10.1", features = ["serde"] }
serde_json = { workspace = true }

# Workspace dependencies
databend-common-arrow = { path = "../../common/arrow" }
databend-common-exception = { path = "../../common/exception" }
databend-common-expression = { path = "../expression" }
databend-common-io = { path = "../../common/io" }
databend-common-meta-app = { path = "../../meta/app" }
databend-common-settings = { path = "../settings" }
databend-storages-common-blocks = { path = "../storages/common/blocks" }
databend-storages-common-table-meta = { path = "../storages/common/table_meta" }
jsonb = { workspace = true }

[dev-dependencies]
databend-common-arrow = { path = "../../common/arrow" }
tokio = { workspace = true }

pretty_assertions = "1.3.0"

[package.metadata.cargo-machete]
ignored = ["match-template"]
