[package]
name = "databend-common-grpc"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[dependencies] # In alphabetical order
# Workspace dependencies
databend-common-base = { path = "../base" }
databend-common-exception = { path = "../exception" }

# GitHub dependencies

# Crates.io dependencies
anyerror = { workspace = true }
hickory-resolver = "0.24"
hyper = "0.14.20"
jwt-simple = "0.11.0"
log = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tonic = { workspace = true }

[build-dependencies]

[features]
mocks = []
