[package]
name = "databend-common-storages-hive"
version = "0.1.0"
edition = "2021"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[dependencies]
databend-common-arrow = { path = "../../../../common/arrow" }
databend-common-base = { path = "../../../../common/base" }
databend-common-catalog = { path = "../../../catalog" }
databend-common-exception = { path = "../../../../common/exception" }
databend-common-expression = { path = "../../../expression" }
databend-common-functions = { path = "../../../functions" }
databend-common-meta-app = { path = "../../../../meta/app" }
databend-common-meta-types = { path = "../../../../meta/types" }
databend-common-pipeline-core = { path = "../../../pipeline/core" }
databend-common-pipeline-sources = { path = "../../../pipeline/sources" }
databend-common-sql = { path = "../../../sql" }
databend-common-storage = { path = "../../../../common/storage" }

databend-storages-common-cache = { path = "../../common/cache" }
databend-storages-common-cache-manager = { path = "../../common/cache_manager" }
databend-storages-common-index = { path = "../../common/index" }
databend-storages-common-table-meta = { path = "../../common/table_meta" }

async-backtrace = { workspace = true }
async-recursion = "1.0.0"
async-trait = { workspace = true }
chrono = { workspace = true }
faststr = "0.2"
futures = { workspace = true }
hive_metastore = "0.0.2"
log = { workspace = true }
minitrace = { workspace = true }
opendal = { workspace = true }
ordered-float = { workspace = true }
serde = { workspace = true }
typetag = { workspace = true }
volo-thrift = "0.9"
