[package]
name = "databend-common-pipeline-sinks"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[dependencies]
databend-common-base = { path = "../../../common/base" }
databend-common-catalog = { path = "../../catalog" }
databend-common-exception = { path = "../../../common/exception" }
databend-common-expression = { path = "../../expression" }
databend-common-pipeline-core = { path = "../core" }

async-backtrace = { workspace = true }
async-channel = "1.7.1"
async-trait = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
