[package]
name = "databend-enterprise-stream-handler"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[dependencies]
# Workspace dependencies
databend-common-base = { path = "../../../common/base" }
databend-common-catalog = { path = "../../catalog" }
databend-common-exception = { path = "../../../common/exception" }
databend-common-meta-app = { path = "../../../meta/app" }
databend-common-sql = { path = "../../sql" }

# Github dependencies
async-backtrace = { workspace = true }
async-trait = { workspace = true }

[build-dependencies]
