[package]
name = "databend-common-tracing"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[features]
console = ["console-subscriber", "tracing", "tracing-subscriber"]

[dependencies] # In alphabetical order
# Workspace dependencies
databend-common-base = { path = "../base" }

# Crates.io dependencies
console-subscriber = { version = "0.2.0", optional = true }
defer = "0.2"
fern = "0.6.2"
humantime = "2.1.0"
itertools = { workspace = true }
log = { workspace = true }
minitrace = { workspace = true }
minitrace-opentelemetry = "0.6"
opentelemetry = { version = "0.21", features = ["trace", "logs"] }
opentelemetry-otlp = { version = "0.14", features = ["trace", "logs", "grpc-tonic"] }
opentelemetry_sdk = { version = "0.21", features = ["trace", "logs", "rt-tokio"] }
serde = { workspace = true }
serde_json = { workspace = true }
tonic = { workspace = true }
tracing = { version = "0.1.40", optional = true }
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "json", "valuable"], optional = true }
