[package]
name = "databend-common-building"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[dependencies]
anyhow = { workspace = true }
cargo-license = "0.5.1"
# old version required by cargo-license
cargo_metadata = "0.15"
gix = "0.52.0"
log = { workspace = true }
vergen = { version = "8.2.4", default-features = false, features = ["build", "cargo", "git", "gix", "rustc"] }
