[package]
name = "databend-common-storages-null"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[dependencies]
databend-common-catalog = { path = "../../catalog" }
databend-common-exception = { path = "../../../common/exception" }
databend-common-expression = { path = "../../expression" }
databend-common-meta-app = { path = "../../../meta/app" }
databend-common-pipeline-core = { path = "../../pipeline/core" }
databend-common-pipeline-sinks = { path = "../../pipeline/sinks" }
databend-common-pipeline-sources = { path = "../../pipeline/sources" }

async-backtrace = { workspace = true }
async-trait = { workspace = true }

[build-dependencies]
databend-common-building = { path = "../../../common/building" }
