[package]
name = "databend-common-http"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false
test = false

[features]
memory-profiling = ["tempfile"]

[dependencies]
# Workspace dependencies
databend-common-base = { path = "../base" }
databend-common-exception = { path = "../exception" }

# GitHub dependencies

# Crates.io dependencies
anyerror = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
poem = { workspace = true }
serde = { workspace = true }
tempfile = { version = "3.4.0", optional = true }
thiserror = { workspace = true }

[dev-dependencies]
pretty_assertions = "1.3.0"
