[package]
name = "databend-common-storages-stage"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[dependencies]
databend-common-base = { path = "../../../common/base" }
databend-common-catalog = { path = "../../catalog" }
databend-common-compress = { path = "../../../common/compress" }
databend-common-exception = { path = "../../../common/exception" }
databend-common-expression = { path = "../../expression" }
databend-common-formats = { path = "../../formats" }
databend-common-meta-app = { path = "../../../meta/app" }
databend-common-pipeline-core = { path = "../../pipeline/core" }
databend-common-pipeline-sources = { path = "../../pipeline/sources" }
databend-common-pipeline-transforms = { path = "../../pipeline/transforms" }
databend-common-settings = { path = "../../settings" }
databend-common-storage = { path = "../../../common/storage" }
databend-common-storages-parquet = { path = "../parquet" }

async-backtrace = { workspace = true }
async-trait = { workspace = true }
csv-core = "0.1.11"
dashmap = { workspace = true }
log = { workspace = true }
opendal = { workspace = true }
parking_lot = { workspace = true }
serde = { workspace = true }

typetag = { workspace = true }
uuid = { workspace = true }

[build-dependencies]
databend-common-building = { path = "../../../common/building" }
