[package]
name = "databend-storages-common-cache-manager"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[features]

[dependencies]
arrow = { workspace = true }
databend-common-arrow = { path = "../../../../common/arrow" }
databend-common-base = { path = "../../../../common/base" }
databend-common-cache = { path = "../../../../common/cache" }
databend-common-catalog = { path = "../../../catalog" }
databend-common-config = { path = "../../../config" }
databend-common-exception = { path = "../../../../common/exception" }
databend-storages-common-cache = { path = "../../common/cache" }
databend-storages-common-index = { path = "../../common/index" }
databend-storages-common-table-meta = { path = "../table_meta" }

log = { workspace = true }
