[package]
name = "databend-storages-common-blocks"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[dependencies]
databend-common-arrow = { path = "../../../../common/arrow" }
databend-common-config = { path = "../../../config" }
databend-common-exception = { path = "../../../../common/exception" }
databend-common-expression = { path = "../../../expression" }
parquet-format-safe = "0.2"
parquet_rs = { workspace = true }

databend-storages-common-table-meta = { path = "../table_meta" }

[build-dependencies]
