[package]
name = "databend-meta"
description = "distributed meta data service"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[features]
default = ["simd"]
memory-profiling = ["databend-common-base/memory-profiling", "databend-common-http/memory-profiling"]
simd = ["databend-common-arrow/simd"]
tokio-console = ["databend-common-tracing/console", "databend-common-base/tracing"]
io-uring = [
    "sled/io_uring",
    "databend-common-meta-sled-store/io-uring",
    "databend-common-meta-raft-store/io-uring",
]

enable-histogram = ["databend-common-metrics/enable-histogram"]

[dependencies]
# Workspace dependencies
databend-common-arrow = { path = "../../common/arrow" }
databend-common-base = { path = "../../common/base" }
databend-common-grpc = { path = "../../common/grpc" }
databend-common-http = { path = "../../common/http" }
databend-common-meta-api = { path = "../api" }
databend-common-meta-client = { path = "../client" }
databend-common-meta-kvapi = { path = "../kvapi" }
databend-common-meta-raft-store = { path = "../raft-store" }
databend-common-meta-sled-store = { path = "../sled-store" }
databend-common-meta-stoerr = { path = "../stoerr" }
databend-common-meta-types = { path = "../types" }
databend-common-metrics = { path = "../../common/metrics" }
databend-common-tracing = { path = "../../common/tracing" }

# GitHub dependencies
sled = { workspace = true }

# Crates.io dependencies
anyerror = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
backon = "0.4"
clap = { workspace = true }
derive_more = { workspace = true }
feature-set = { workspace = true }
futures = { workspace = true }
futures-async-stream = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
logcall = { workspace = true }
maplit = "1.0.2"
minitrace = { workspace = true }
poem = { workspace = true }
prometheus-client = "0.22"
prost = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serfig = { workspace = true }
tokio-stream = { workspace = true }
tonic = { workspace = true }
tonic-reflection = { workspace = true }

[dev-dependencies]
env_logger = "0.10.0"
maplit = "1.0.2"
pretty_assertions = "1.3.0"
regex = { workspace = true }
reqwest = { workspace = true }
temp-env = "0.3.0"
tempfile = "3.4.0"
test-harness = "0.1.1"

[build-dependencies]
databend-common-building = { path = "../../common/building" }
