[package]
name = "databend-common-vector"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[dependencies] # In alphabetical order
databend-common-exception = { path = "../exception" }

ndarray = "0.15.6"

[build-dependencies]

[features]

[dev-dependencies]
approx = "0.5.1"
