[package]
name = "bendpy"
version = "0.0.0"
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[build-dependencies]
pyo3-build-config = "0.18.3"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "databend"
crate-type = ["cdylib"]

[dependencies]
# Workspace dependencies
arrow = { workspace = true, features = ["pyarrow"] }
arrow-schema = { workspace = true }

databend-common-config = { path = "../query/config" }
databend-common-exception = { path = "../common/exception" }
databend-common-expression = { path = "../query/expression" }
databend-common-license = { path = "../common/license" }
databend-common-meta-app = { path = "../meta/app" }
databend-common-meta-embedded = { path = "../meta/embedded" }
databend-common-meta-types = { path = "../meta/types" }
databend-common-users = { path = "../query/users" }
databend-query = { path = "../query/service", features = [
    "simd",
    "disable_initial_exec_tls",
], default-features = false }

# # Crates.io dependencies
ctor = "0.2.5"
pyo3 = { version = "0.20", features = ["extension-module", "abi3", "abi3-py37"] }
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread", "sync"] }
tokio-stream = { workspace = true }
uuid = { workspace = true }
