[package]
name = "databend-enterprise-data-mask-feature"
description = "data mask"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[dependencies]
# Workspace dependencies
databend-common-base = { path = "../../../common/base" }
databend-common-exception = { path = "../../../common/exception" }
databend-common-meta-app = { path = "../../../meta/app" }
databend-common-meta-store = { path = "../../../meta/store" }

async-trait = { workspace = true }

[build-dependencies]
