[package]
name = "databend-common-users"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[features]
io-uring = ["databend-common-meta-store/io-uring"]

[dependencies] # In alphabetical order
# Workspace dependencies
databend-common-ast = { path = "../ast" }
databend-common-base = { path = "../../common/base" }
databend-common-exception = { path = "../../common/exception" }
databend-common-grpc = { path = "../../common/grpc" }
databend-common-management = { path = "../management" }
databend-common-meta-app = { path = "../../meta/app" }
databend-common-meta-kvapi = { path = "../../meta/kvapi" }
databend-common-meta-store = { path = "../../meta/store" }
databend-common-meta-types = { path = "../../meta/types" }

# GitHub dependencies

# Crates.io dependencies
async-backtrace = { workspace = true }
base64 = "0.21"
chrono = { workspace = true }
cidr = { version = "0.2.2" }
enumflags2 = { workspace = true }
jwt-simple = "0.11"
log = { workspace = true }
p256 = "0.13"
parking_lot = { workspace = true }
passwords = { version = "3.1.16", features = ["common-password"] }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
databend-common-expression = { path = "../expression" }
pretty_assertions = "1.3.0"
wiremock = "0.5.14"
