[package]
name = "databend-common-sharing"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
databend-common-auth = { path = "../../common/auth" }
databend-common-base = { path = "../../common/base" }
databend-common-config = { path = "../config" }
databend-common-exception = { path = "../../common/exception" }
databend-common-meta-api = { path = "../../meta/api" }
databend-common-meta-app = { path = "../../meta/app" }
databend-common-storage = { path = "../../common/storage" }
databend-common-users = { path = "../users" }

async-backtrace = { workspace = true }
http = "0.2"
log = { workspace = true }
moka = "0.12"
opendal = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
