[package]
name = "databend-enterprise-vacuum-handler"
description = "vacuum handler"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[dependencies]
# Workspace dependencies
databend-common-base = { path = "../../../common/base" }
databend-common-catalog = { path = "../../catalog" }
databend-common-exception = { path = "../../../common/exception" }
databend-common-storages-fuse = { path = "../../storages/fuse" }

async-backtrace = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }

[build-dependencies]
